/**
 * Regenerates sitemap.xml from the pages that declare themselves indexable.
 *
 * A page is included only if it carries a <link rel="canonical">, and the
 * canonical href is used verbatim as the <loc>. That keeps the sitemap and the
 * canonicals from ever disagreeing, drops demo pages, fragments and duplicate
 * result views without a maintained exclusion list, and collapses pages that
 * canonicalise to the same URL. <lastmod> comes from the file's last commit so
 * the dates stay honest.
 *
 * Usage: node scripts/generate-sitemap.mjs [--check]
 *   --check exits 1 without writing if sitemap.xml is out of date (for CI).
 */
import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(repoRoot, 'sitemap.xml');
const checkOnly = process.argv.includes('--check');

/* Roots to scan. Everything else at the repo root is app code, add-in dialogs
   or tooling, all of which robots.txt disallows. */
const SCAN_DIRS = ['Statistico-Website'];

/* Directories never worth crawling for candidates, regardless of markup. */
const SKIP_DIRS = new Set(['assets', 'demos', 'legacy-help', 'node_modules', '.git']);

/* Crawl priority and change frequency by URL shape. First match wins; Google
   ignores both hints, but Bing still reads changefreq and they cost nothing. */
const RANKS = [
  [/^https:\/\/statistico\.live\/$/, '1.0', 'weekly'],
  [/index-Analytics\.html$/, '0.9', 'weekly'],
  [/index-(Calculators|Addins|EzPaste)\.html$/, '0.8', 'weekly'],
  [/\/analytics\/[^/]+\.html$/, '0.7', 'monthly'],
  [/(how-it-works|why-another-package|faq)\.html$/, '0.6', 'monthly'],
  [/\/ezpaste\/docs\//, '0.6', 'monthly'],
  [/(about-us|contact)\.html$/, '0.5', 'monthly'],
  [/(terms-and-conditions|privacy-policy)\.html$/, '0.3', 'yearly'],
];

function rankFor(loc) {
  const hit = RANKS.find(([re]) => re.test(loc));
  return hit ? { priority: hit[1], changefreq: hit[2] } : { priority: '0.5', changefreq: 'monthly' };
}

function walk(dir, found = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(path.join(dir, entry.name), found);
    } else if (entry.name.endsWith('.html')) {
      found.push(path.join(dir, entry.name));
    }
  }
  return found;
}

function canonicalOf(file) {
  const head = fs.readFileSync(file, 'utf8').slice(0, 8000);
  const m = head.match(/<link[^>]+rel=["']canonical["'][^>]*>/i);
  const href = m && m[0].match(/href=["']([^"']+)["']/i);
  return href ? href[1].trim() : null;
}

function lastModified(file) {
  const rel = path.relative(repoRoot, file).split(path.sep).join('/');
  try {
    const committed = execFileSync('git', ['log', '-1', '--format=%cs', '--', rel], {
      cwd: repoRoot,
      encoding: 'utf8',
    }).trim();
    if (committed) return committed;
  } catch {
    /* not a checkout, or git unavailable: fall through to mtime */
  }
  return fs.statSync(file).mtime.toISOString().slice(0, 10);
}

const pages = new Map();
for (const dir of SCAN_DIRS) {
  for (const file of walk(path.join(repoRoot, dir))) {
    const loc = canonicalOf(file);
    if (!loc) continue;
    const lastmod = lastModified(file);
    /* Several files can share one canonical; keep the most recent date. */
    const prev = pages.get(loc);
    if (!prev || prev.lastmod < lastmod) pages.set(loc, { loc, lastmod });
  }
}

const entries = [...pages.values()]
  .map((p) => ({ ...p, ...rankFor(p.loc) }))
  .sort((a, b) => Number(b.priority) - Number(a.priority) || a.loc.localeCompare(b.loc));

/* A page that carries a canonical but sits under a disallowed path would be
   submitted and then refused, which Search Console reports as an error. */
const disallowed = fs
  .readFileSync(path.join(repoRoot, 'robots.txt'), 'utf8')
  .split(/\r?\n/)
  .map((line) => line.replace(/#.*$/, '').trim())
  .filter((line) => /^Disallow:/i.test(line))
  .map((line) => line.split(':').slice(1).join(':').trim())
  .filter(Boolean);

const blocked = entries.filter((e) =>
  disallowed.some((rule) => new URL(e.loc).pathname.startsWith(rule))
);
if (blocked.length) {
  console.error('These pages are in the sitemap but blocked by robots.txt:');
  for (const e of blocked) console.error(`  ${e.loc}`);
  process.exit(1);
}

const xml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  entries
    .map(
      (e) =>
        '  <url>\n' +
        `    <loc>${e.loc}</loc>\n` +
        `    <lastmod>${e.lastmod}</lastmod>\n` +
        `    <changefreq>${e.changefreq}</changefreq>\n` +
        `    <priority>${e.priority}</priority>\n` +
        '  </url>\n'
    )
    .join('') +
  '</urlset>\n';

const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : '';
if (checkOnly) {
  if (current !== xml) {
    console.error('sitemap.xml is out of date - run: node scripts/generate-sitemap.mjs');
    process.exit(1);
  }
  console.log(`sitemap.xml is up to date (${entries.length} URLs).`);
} else {
  fs.writeFileSync(outFile, xml);
  console.log(`Wrote sitemap.xml with ${entries.length} URLs.`);
  for (const e of entries) console.log(`  ${e.lastmod}  ${e.priority}  ${e.loc}`);
}
